### ISSUE TITLE
do not include .Rmd in _gh-pages

### ISSUE THREAD

**Issue by schloerke** [schloerke/packagedocs#10]
these are not useful and will not be listened to

**Comment by hafen** [comment]
would be good if we can omit them on inst/docs too unless it is too hacky

**Comment by schloerke** [comment]
when calling `build_vignettes()`, I will remove them.

**Comment by schloerke** [comment]
https://github.com/schloerke/packagedocs/compare/46176bd...827ee64?expand=1
