### ISSUE TITLE
add more information in vignette about setup

### ISSUE THREAD

**Issue by hafen** [schloerke/packagedocs#13]
It would be good to talk about putting the VignetteBuilder field in DESCRIPTION, adding packagedocs as suggests, updating .gitignore and .Rbuildignore, etc.

**Comment by schloerke** [comment]
added to the init method.  This should be handled in there automatically.

**Comment by schloerke** [comment]
https://github.com/schloerke/packagedocs/compare/37bcd10...a9f6405?expand=1
