### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by schloerke** [schloerke/packagedocs#3]
@hafen

So if we are setting up this drat repo, I think we should just fork staticdocs and lazyrmd to HBGDki.

This would "build" the packages and it would keep them separate.

... or move all code into packagedocs?

- Barret

**Comment by schloerke** [comment]
Then again, it would be nice to have on CRAN.  Therefore lazyrmd needs to be put on CRAN.  I'll copy over staticdocs as there is no intent to make that on CRAN for a long time

**Comment by hafen** [comment]
Correct - CRAN is a priority.  Thanks!
